### ISSUE TITLE
Non-Lua overlay sometimes overlays too much when saving changes from pico8

### ISSUE THREAD

**Issue by Kaali** [Kaali/pico8-mode#12]
Seems to usually happen when editing map data.

**Comment by bartsnapp** [comment]
Is this what covers up stuff like:

pico-8 cartridge // http://www.pico-8.com
version 16
__lua__

because, yes, it sometimes covers up too much of my code too.

**Comment by Kaali** [comment]
Yes, it's that feature. I should look into why it covers too much. For now you can turn it off with the custom parameter `pico8-dim-non-code-sections` by setting it to `nil`

**Comment by Kaali** [comment]
It would be great if you could find a way to consistently repeat the problem. I have an idea how to fix it, but it would be nice to know if it works rather than guess.

**Comment by bartsnapp** [comment]
OK! I'll keep a look out. Also I really do lijke the mode! I think it is really cool how the sprites show up.

**Comment by bartsnapp** [comment]
It happens to me when I use the linux-middle click to paste

**Comment by Kaali** [comment]
Oh. That's interesting, then the bug is not where I thought it was.

Does it matter where you paste?

**Comment by Kaali** [comment]
It's quit hard to duplicate reliably. But now the code has been modified (70a8d7ddc13bca6d59becee8cc2d57bb292c1da4) and I couldn't replicate it anymore.

**Comment by bartsnapp** [comment]
Great! I'll check it out!
