### ISSUE TITLE
Mode does not work on Emacs 25.1

### ISSUE THREAD

**Issue by hvrauhal** [Kaali/pico8-mode#6]
Trying to load a .p8 file gives an error:
```
File mode specification error: (void-function string-join)
```

At least `string-join` is [not yet in 25.1](https://www.emacswiki.org/emacs/ElispCookbook#toc8).

**Comment by Kaali** [comment]
Fixed in ff11c2fdf639a5391480ee4b5813e8423f319b49

**Comment by Kaali** [comment]
Still need to fix (when-let*)

**Comment by Kaali** [comment]
Fixed when-let in 6121791
